---
abstract: 'Log to Elasticsearch'
author:
  - 'Alexei Pastuchov<palik@cpan.org>'
build_requires:
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Log4perl-Appender-Elasticsearch
no_index:
  directory:
    - t
    - inc
requires:
  Data::UUID::LibUUID: 0.05
  HTTP::Headers: 6.05
  HTTP::Request: 6
  JSON: 2.61
  LWP::UserAgent: 6.05
  Log::Log4perl: 1.41
  MIME::Base64: 3.13
  URI: 1.6
  perl: 5.006
version: 0.01
